using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Items.Prism {
    [TableName ("prism_items")]
    public class PrismNpcItemRecord : ItemRecord<PrismNpcItemRecord>, IAutoGeneratedRecord {
        private int m_ownerId;

        public int OwnerId {
            get { return m_ownerId; }
            set {
                m_ownerId = value;
                IsDirty = true;
            }
        }
    }
}