using Stump.DofusProtocol.Types;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.Characters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Stump.Server.WorldServer.Database.Shortcuts
{
    public class EmoteShortcutRelator
    {
        public static string FetchQuery = "SELECT * FROM characters_shortcuts_Emote";

        /// <summary>
        /// Use string.Format
        /// </summary>
        public static string FetchByOwner = "SELECT * FROM characters_shortcuts_Emote WHERE OwnerId={0}";
    }

    [TableName("characters_shortcuts_Emote")]
    public class EmoteShortcut : Shortcut, IAutoGeneratedRecord
    {
        public EmoteShortcut()
        {
        }

        public EmoteShortcut(CharacterRecord owner, int slot, int emoteId)
            : base(owner, slot)
        {
            EmoteId = emoteId;
        }

        private int m_emoteId;

        public int EmoteId
        {
            get { return m_emoteId; }
            set
            {
                m_emoteId = value;
                IsDirty = true;
            }
        }

        public override DofusProtocol.Types.Shortcut GetNetworkShortcut()
        {
            return new ShortcutEmote((sbyte)Slot, (byte)EmoteId);
        }
    }
}
