using Stump.DofusProtocol.Types;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.Characters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Stump.Server.WorldServer.Database.Shortcuts
{
    public class SmileyShortcutRelator
    {
        public static string FetchQuery = "SELECT * FROM characters_shortcuts_Smiley";

        /// <summary>
        /// Use string.Format
        /// </summary>
        public static string FetchByOwner = "SELECT * FROM characters_shortcuts_Smiley WHERE OwnerId={0}";
    }

    [TableName("characters_shortcuts_Smiley")]
    public class SmileyShortcut : Shortcut, IAutoGeneratedRecord
    {
        public SmileyShortcut()
        {
        }

        public SmileyShortcut(CharacterRecord owner, int slot, int smileyId)
            : base(owner, slot)
        {
            SmileyId = smileyId;
        }

        private int m_smileyId;

        public int SmileyId
        {
            get { return m_smileyId; }
            set
            {
                m_smileyId = value;
                IsDirty = true;
            }
        }

        public override DofusProtocol.Types.Shortcut GetNetworkShortcut()
        {
            return new ShortcutSmiley((sbyte)Slot, (ushort)SmileyId);
        }
    }
}
