using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using System;

namespace Stump.Server.WorldServer.Database.Llavero
{
    [TableName("characters_llavero")]
    public class LlaveroRecord : IAutoGeneratedRecord
    {
        [PrimaryKey("Id")]
        public int Id { get; set; }
        public int CharacterId { get; set; }
        public int LlaveId { get; set; }
        public DateTime Time { get; set; }
        [Ignore]
        public bool IsNew { get; set; }
        [Ignore]
        public bool IsUpdated { get; set; }
    }
}
