using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using System;

namespace Stump.Server.WorldServer.Database.Almanax
{
    [TableName("characters_almanax")]
    public class AlmanaxRecord : IAutoGeneratedRecord
    {
        [PrimaryKey("Id")] 
        public int Id { get; set; }
        public int CharacterId { get; set; }
        public int AlmanaxDia { get; set; }
        public DateTime Time { get; set; }
        public string Ip { get; set; }
        [Ignore]
        public bool IsNew { get; set; }
        [Ignore]
        public bool IsUpdated { get; set; }
    }
}
