using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using System;

namespace Database.Almanax
{
    [TableName("almanax_items")]
    public class AlmanaxItemRecord : IAutoGeneratedRecord
    {
        [PrimaryKey("Id")] 
        public int Id { get; set; }
        public DateTime Time { get; set; }
        public int itemId { get; set; }
        public int cantidad { get; set; }
    }
}
