using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.Items.Templates;
using Stump.Server.WorldServer.Game.Items;
//By Saiki for Wolf
namespace Stump.Server.WorldServer.Database.Mounts.Capture
{
    class VulkRelator
    {
        public static string FetchQuery = "SELECT * FROM capture_vulk_drops";
    }


    [TableName("capture_vulk_drops")]
    public class VulkRecord : IAutoGeneratedRecord
    {

        private ItemTemplate m_template;

        [PrimaryKey("MonsterId")]
        public int MonsterId
        {
            get;
            set;
        }

        public int DropId
        {
            get;
            set;
        }

        public int TauxDrop
        {
            get;
            set;
        }

        public ItemTemplate ItemTemplate => m_template ?? (m_template = ItemManager.Instance.TryGetTemplate(DropId));

    }
}
